# Generated by Django 5.2.13 on 2026-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'eSewa')], max_length=20),
        ),
    ]
