# Generated by Django 5.2.13 on 2026-05-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatar/default.jpg",
                help_text="Profile photo",
                null=True,
                upload_to="avatar/",
            ),
        ),
    ]
