# Generated by Django 5.2.13 on 2026-05-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("player", "Player")],
                default="client",
                max_length=10,
            ),
        ),
    ]
