# Generated by Django 5.2.13 on 2026-05-01 15:53

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('amenities', models.JSONField(default=dict, help_text='e.g., lights, parking, washroom')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, help_text='Cached average rating', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
            ],
            options={
                'verbose_name': 'Turf',
                'verbose_name_plural': 'Turfs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TurfImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='turf_images/')),
                ('is_cover', models.BooleanField(default=False, help_text='Display as cover image')),
                ('order', models.IntegerField(default=0, help_text='Display order for images')),
            ],
            options={
                'verbose_name': 'Turf Image',
                'verbose_name_plural': 'Turf Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TurfSport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.CharField(choices=[('futsal', 'Futsal'), ('basketball', 'Basketball'), ('badminton', 'Badminton'), ('cricket', 'Cricket'), ('volleyball', 'Volleyball'), ('tennis', 'Tennis')], max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_players', models.IntegerField()),
                ('court_count', models.IntegerField(help_text='Number of courts available')),
            ],
            options={
                'verbose_name': 'Turf Sport',
                'verbose_name_plural': 'Turf Sports',
                'ordering': ['turf', 'sport'],
            },
        ),
    ]
