# Generated by Django 5.2.13 on 2026-05-19 16:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Turf",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("futsal", "Futsal"),
                            ("basketball", "Basketball"),
                            ("badminton", "Badminton"),
                            ("cricket", "Cricket"),
                            ("volleyball", "Volleyball"),
                            ("tennis", "Tennis"),
                            ("pickleball", "Pickleball"),
                            ("table_tennis", "Table Tennis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. Court A - Futsal", max_length=200),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price_per_hour",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "max_players",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "court_count",
                    models.IntegerField(
                        default=1,
                        help_text="Number of courts available for this sport",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                (
                    "avg_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Cached average rating — update via signal or periodic task",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Soft delete timestamp", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Turf",
                "verbose_name_plural": "Turfs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TurfReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Turf Review",
                "verbose_name_plural": "Turf Reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="e.g. KTM Sports Hub", max_length=200),
                ),
                (
                    "location",
                    models.CharField(help_text="Physical address", max_length=255),
                ),
                (
                    "amenities",
                    models.JSONField(
                        default=dict,
                        help_text="Shared facilities e.g. {'parking': true, 'lights': true, 'washroom': true}",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Soft delete timestamp", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue",
                "verbose_name_plural": "Venues",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TurfImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="turf_images/")),
                (
                    "is_cover",
                    models.BooleanField(
                        default=False, help_text="Mark as the cover/thumbnail image"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order, lower = first"
                    ),
                ),
                (
                    "turf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="turfs.turf",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turf Image",
                "verbose_name_plural": "Turf Images",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
