# Generated by Django 5.2.14 on 2026-05-23 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turfs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turfreview',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turf_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turfreview',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='turfs.turf'),
        ),
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turf',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turfs', to='turfs.venue'),
        ),
        migrations.AddConstraint(
            model_name='turfimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('turf',), name='unique_cover_per_turf'),
        ),
        migrations.AlterUniqueTogether(
            name='turfreview',
            unique_together={('turf', 'client')},
        ),
    ]
