# Generated by Django 5.2.14 on 2026-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='is_active',
        ),
        migrations.AddField(
            model_name='turf',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='draft', max_length=20),
        ),
    ]
