# Generated by Django 5.2.14 on 2026-05-24 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0003_remove_turf_is_active_remove_venue_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizenship_front', models.ImageField(upload_to='venue_verification/citizenship/')),
                ('citizenship_back', models.ImageField(upload_to='venue_verification/citizenship/')),
                ('pan_card', models.ImageField(upload_to='venue_verification/pan/')),
                ('business_registration', models.ImageField(upload_to='venue_verification/business/')),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='turfimage',
            name='unique_cover_per_turf',
        ),
        migrations.RemoveField(
            model_name='turfimage',
            name='is_cover',
        ),
        migrations.AddField(
            model_name='venue',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/covers/'),
        ),
        migrations.AddField(
            model_name='venueverification',
            name='venue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='turfs.venue'),
        ),
    ]
