# Generated by Django 5.2.14 on 2026-05-27 16:33

import apps.turfs.save_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0004_venueverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfimage',
            name='image',
            field=models.ImageField(upload_to=apps.turfs.save_image.turf_image_path),
        ),
        migrations.AlterField(
            model_name='venue',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.turfs.save_image.venue_cover_path),
        ),
        migrations.AlterField(
            model_name='venueverification',
            name='business_registration',
            field=models.FileField(upload_to=apps.turfs.save_image.venue_verification_path),
        ),
        migrations.AlterField(
            model_name='venueverification',
            name='citizenship_back',
            field=models.FileField(upload_to=apps.turfs.save_image.venue_verification_path),
        ),
        migrations.AlterField(
            model_name='venueverification',
            name='citizenship_front',
            field=models.FileField(upload_to=apps.turfs.save_image.venue_verification_path),
        ),
        migrations.AlterField(
            model_name='venueverification',
            name='pan_card',
            field=models.FileField(upload_to=apps.turfs.save_image.venue_verification_path),
        ),
    ]
