# Generated by Django 5.2.13 on 2026-05-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Associated match if this booking is linked to a match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='matches.match'),
        ),
    ]
