# Generated by Django 5.2.13 on 2026-05-19 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0002_initial"),
        ("turfs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="turf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="turfs.turf",
            ),
        ),
    ]
