# Generated by Django 5.2.13 on 2026-05-19 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["user", "-created_at"], name="bookings_bo_user_id_6151bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["turf", "date"], name="bookings_bo_turf_id_a88dc5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("turf", "date", "start_time")},
        ),
    ]
