# Generated by Django 5.2.13 on 2026-05-01 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('chat', 'Chat'), ('match', 'Match'), ('review', 'Review'), ('system', 'System')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.CharField(blank=True, help_text='ID of related object (booking, payment, etc)', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
