# Generated by Django 5.2.14 on 2026-05-23 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.CharField(max_length=50)),
                ('match_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('format', models.CharField(help_text='e.g., 5v5, 3v3, 7v7', max_length=50)),
                ('slots_needed', models.IntegerField(help_text='How many more players needed')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('mid', 'Intermediate'), ('pro', 'Professional')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('location_text', models.CharField(help_text='Area/city description', max_length=255)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-match_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('team', models.CharField(blank=True, choices=[('A', 'Team A'), ('B', 'Team B')], help_text='Team assignment', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Match Participant',
                'verbose_name_plural': 'Match Participants',
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
