# Generated by Django 5.2.14 on 2026-05-23 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('turfs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='turf',
            field=models.ForeignKey(blank=True, help_text='Associated turf, nullable for auto-booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='turfs.turf'),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['-match_date', 'status'], name='matches_mat_match_d_567d4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchparticipant',
            unique_together={('match', 'user')},
        ),
    ]
